### ISSUE TITLE
__GNUC_GNU_INLINE__ and always_inline

### ISSUE THREAD

**Issue by eustas** [nemequ/hedley#10]
https://github.com/nemequ/hedley/blob/913adf3bbcd42224e460154b47c789676d7b0130/hedley.h#L900

If `__GNUC_GNU_INLINE__==1`, then `HEDLEY_INLINE HEDLEY_ALWAYS_INLINE foo()` will cause compiler warning.

The problem is that `HEDLEY_INLINE` is empty in this case. Compiler says that you can not always inline something that is not inlined at all.

Not sure how to deal with that. There is `gnu_inline` that does the converse to what I want (i.e. `inline` with gnu90 semantic), but no way say that we want std inline (or `__inline__` is what we want?)

Anyways, defining `HEDLEY_INLINE` either as `inline` or as `__inline__` "solves" the problem; not sure if it is correct.

**Comment by nemequ** [comment]
I'm thinking

```patch
diff --git a/hedley.h b/hedley.h
index 08d9a7d..b50dff9 100644
--- a/hedley.h
+++ b/hedley.h
@@ -875,7 +875,7 @@ HEDLEY_DIAGNOSTIC_POP
   (defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)) || \
   (defined(__cplusplus) && (__cplusplus >= 199711L))
 #  define HEDLEY_INLINE inline
-#elif defined(__GNUC_STDC_INLINE__) || HEDLEY_ARM_VERSION_CHECK(6,2,0)
+#elif defined(HEDLEY_GNUC_VERSION) || HEDLEY_ARM_VERSION_CHECK(6,2,0)
 #  define HEDLEY_INLINE __inline__
 #elif \
   HEDLEY_MSVC_VERSION_CHECK(12,0,0) || \
@@ -897,7 +897,7 @@ HEDLEY_DIAGNOSTIC_POP
   HEDLEY_IBM_VERSION_CHECK(10,1,0) || \
   HEDLEY_TI_VERSION_CHECK(8,0,0) || \
   (HEDLEY_TI_VERSION_CHECK(7,3,0) && defined(__TI_GNU_ATTRIBUTE_SUPPORT__))
-#  define HEDLEY_ALWAYS_INLINE __attribute__((__always_inline__))
+#  define HEDLEY_ALWAYS_INLINE __attribute__((__always_inline__)) HEDLEY_INLINE
 #elif HEDLEY_MSVC_VERSION_CHECK(12,0,0)
 #  define HEDLEY_ALWAYS_INLINE __forceinline
 #elif HEDLEY_TI_VERSION_CHECK(7,0,0) && defined(__cplusplus)
```

I don't think we need to worry about GNU vs C99 style inline here.

Also `HEDLEY_INLINE HEDLEY_ALWAYS_INLINE` may confuse some compilers… I think it would be safer to only do `HEDLEY_ALWAYS_INLINE`.

I need to do a bit more testing before I push, though.

**Comment by nemequ** [comment]
Fixed in v7.
