### ISSUE TITLE
User guide still refers to "MIT license"

### ISSUE THREAD

**Issue by travisdowns** [nemequ/hedley#2]
The [user guide](https://nemequ.github.io/hedley/user-guide.html) still says _(it's MIT-licensed)_ at one point. I think that headly is CC0 now.

Also the link at the bottom of the page says "Code licensed under an MIT License,". That latter note may still be correct (perhaps it refers to the code in the user guide, not the code in headly itself) - although it's a bit weird to have the code in the guide licensed more restrictively (MIT is more restrictive than CC0, right?) than the code itself.

**Comment by nemequ** [comment]
I'm not sure how much of the code in the user guide is really copyrightable, but feel free to use it as public domain. I'll switch the docs to CC0 when I have a few minutes.
