### ISSUE TITLE
maybe_unused?

### ISSUE THREAD

**Issue by RedDwarf69** [nemequ/hedley#21]
It's such an obvious one that I'm sure there must be a good reason for not including it, but I can't find anything explaining this.

Could Hedley have a macro for

* C++17 [[maybe_unused]] (https://en.cppreference.com/w/cpp/language/attributes/maybe_unused)
* gcc attribute unused (https://gcc.gnu.org/onlinedocs/gcc/Common-Variable-Attributes.html#Common-Variable-Attributes)
* clang attribute unused (https://clang.llvm.org/docs/AttributeReference.html)

?

**Comment by nemequ** [comment]
The reason is that compiler support is relatively limited, but there is a more portable way to do this on every compiler I'm aware of that supports such a warning:

    void foo(int bar) {
      (void) bar;
    }

TBH I don't see a reason to use the `unused` attribute.  I could be persuaded to add it if there is demand, though…

**Comment by RedDwarf69** [comment]
From what I see the C and C++ standards actually explicitly state the cast to void thing as a valid way of discarding stuff (http://www.csci.csusb.edu/dick/c++std/cd2/expr.html), so it seems 100% portable.

In the paper to add maybe_unused to C++17 (http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0068r0.pdf) it does mention the cast to void option as part of a group of alternatives, but it doesn't explicitly say of any specific problem with it. It just argues that `By standardizing the [[unused]] attribute we would provide a common, portable and more readable way toexpress this intent.`

So I'm convinced, I don't see a reason to use the unused attribute either. Let's close this.

**Comment by nemequ** [comment]
Nice.  I didn't remember that being in the standards.  Thank you for pointing it out :)

Just for future reference:

For [C99](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf) see §6.8.3¶4 (which was §3.6.3¶4 in C89):

> If a function call is evaluated as an expression statement for its side effects only, the discarding of its value may be made explicit by converting the expression to a void expression by means of a cast:
>
>     int p(int);
>     /* … */
>     (void)p(0);

For C++ there is §5.2.9¶4 (in the working draft from 1996 you linked to above, so I guess C++98).  In C++17 it's §8.2.9¶6:

> Any expression can be explicitly converted to type *cv* `void`, in which case it becomes a discarded-value expression (Clause 8). [ *Note:* However, if the value is in a temporary object (15.2), the destructor for that object is not executed until the usual time, and the value of the object is preserved for the purpose of executing the destructor. — *end note* ]
