### ISSUE TITLE
HEDLEY_ALWAYS_INLINE w/o inline specifier

### ISSUE THREAD

**Issue by travisdowns** [nemequ/hedley#23]
The documentation for `HEDLEY_ALWAYS_INLINE` gives the following example:

```
HEDLEY_ALWAYS_INLINE
void do_something_quickly(void);
```

However, even if the function body is included, like:

```
HEDLEY_ALWAYS_INLINE
void do_something_quickly(void) {}
```

This will give a warning with `-Wall` (and fail to compile with `-Werror`):

```
warning: always_inline function might not be inlinable [-Wattributes]
 void do_something_quickly(void) {}
```

See [godbolt](https://godbolt.org/z/yaw76n).

The problem is that the function is not also declared `inline`. I.e., `__attribute__((__always_inline__))` does not imply `inline`. 

Maybe `HEDLEY_ALWAYS_INLINE` should include `inline`, but at a minimum the documentation should be updated.

**Comment by nemequ** [comment]
> Maybe `HEDLEY_ALWAYS_INLINE` should include `inline`

I think so.  What version are you using?  `HEDLEY_ALWAYS_INLINE` should include `HEDLEY_INLINE` since v7.

If that's not it, what compiler versions and flags are you using?

**Comment by travisdowns** [comment]
Oops

    #define HEDLEY_VERSION 1

Sorry, I copied this from somewhere else locally and I must have gotten this old version. Let me check w/ the newest version.

**Comment by travisdowns** [comment]
That was the problem, sorry for the noise.

The one consolation is that I think the documentation is still wrong in that the implementation section doesn't show the fact that inline is included:

![image](https://user-images.githubusercontent.com/2403521/59558999-5b526800-8fc4-11e9-868d-57e52aef5760.png)

**Comment by nemequ** [comment]
Thanks for reporting instead of just adding `HEDLEY_INLINE` to your code; I'd much rather hear about this type of issue.

You're right about the docs being out of date. I just pushed an update, thanks!
