### ISSUE TITLE
Line #689

### ISSUE THREAD

**Issue by Phillrb** [nemequ/hedley#26]
_declspec(deprecated)

should be 

__declspec(deprecated)

**Comment by nemequ** [comment]
Fixed in dev branch, thanks for reporting!

Are you actually using Visual Studio 2003, or were you just reading the code?  I don't have access to VS 2003, so if the former I'm hoping you could run `nmake -f Makefile.msvc` in the test/ directory and paste the result here…

**Comment by Phillrb** [comment]
Sorry, I'm a Linux & Mac user and was just passing by! Happened to notice it whilst looking through the code. I was looking at supporting GCC, GNU & MSVC in a project and needed to silence a few warnings in a safe way that satisfies all 3 compilers. Thanks for sharing this as Open Source.

**Comment by nemequ** [comment]
Oh well, it was worth a try :)

Thanks again for filing the bug.  A lot of people would just keep going in that situation, I really appreciate that you took the time to report it.
