### ISSUE TITLE
HEDLEY_STATIC_ASSERT: static_assert() expects 2 arguments in C++ <17

### ISSUE THREAD

**Issue by aaost** [nemequ/hedley#27]
Hey, there. Evaluating with `gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.11)`
` __cplusplus version = 201402`

Getting these errors:
```
hedley.h:1323:65: error: expected ‘,’ before ‘)’ token
 #  define HEDLEY_STATIC_ASSERT(expr, message) static_assert(expr)

hedley.h:1323:65: error: expected string-literal before ‘)’ token
 #  define HEDLEY_STATIC_ASSERT(expr, message) static_assert(expr)
```
According to the [static_assert()](https://en.cppreference.com/w/cpp/language/static_assert) documentation the function requires 2 arguments until C++17 (and this feature isn't implemented in GCC until v6 according to [GCC docs](https://gcc.gnu.org/projects/cxx-status.html#cxx17)).

Line 1322 in hedley.h is `#elif defined(__cplusplus) && (__cplusplus >= 201103L)` but should probably be `#elif defined(__cplusplus) && (__cplusplus >= 201703L)`
Changing to 201703L fixed the build for me. Wanted to pass this by you to make sure this is indeed a typo and not just a peculiarity of my environment.

**Comment by nemequ** [comment]
Okay, that makes sense; I was worried I was missing something.  Hedley is due for a release anyways, I'll try to do the proper testing and get one out over the weekend, meanwhile I've gone ahead and pushed the fix to the dev branch.

Thanks again for reporting this!

**Comment by aaost** [comment]
Yeah, no problem, thanks for the fix!

**Comment by travisdowns** [comment]
@nemequ FWIW, [this](https://stackoverflow.com/a/83763/149138) is where I look to find free version of the standard. The "Tim Song" links at the bottom are good: the [C++14 version](https://timsong-cpp.github.io/cppwp/n4140/) is N4140 which is basically "better" than the paid version of C++14: it's not a working draft but rather full C++14 plus subsequent "editorial" changes.

AFAIK the C standardsa are totally free these days?
