### ISSUE TITLE
User guide examples are invisible in Chrome, Firefox

### ISSUE THREAD

**Issue by travisdowns** [nemequ/hedley#3]
At least for me, all the examples in the [online API doc](https://nemequ.github.io/hedley/api-reference.html) are invisible.

For example, the [`HEDLEY_NEVER_INLINE`](https://nemequ.github.io/hedley/api-reference.html#HEDLEY_NEVER_INLINE) doc looks like this for me:

![image](https://user-images.githubusercontent.com/2403521/31867990-4c26947c-b75e-11e7-89c5-e5de0d9e505f.png)

If I scroll over the text I can see it:

![image](https://user-images.githubusercontent.com/2403521/31867995-61db0bcc-b75e-11e7-9817-86dab11bc290.png)

My knowledge of HTML and CSS is close enough to zero that I didn't diagnose it beyond that.

**Comment by nemequ** [comment]
Well that's not right... What versions of the browsers, and what OS? They 
work in FF and Chrome here...

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by travisdowns** [comment]
Ubuntu 16.04: `Linux 9550-linux 4.10.0-37-generic #41~16.04.1-Ubuntu` 
I'm using the default Unity desktop environment. I suppose the most likely culprit is some weird unity display issue?
Mozilla Firefox 56.0
Google Chrome 62.0.3202.62

**Comment by jibsen** [comment]
Have the same here in Chrome and FF on Win10. In Chrome it looks like run_prettify.js is not being loaded due to firstly Privacy Badger blocking it, and after enabling it, due to the SHA digest not matching. Guess it's unlucky the fallback ends up being invisible text.

**Comment by nemequ** [comment]
Fixed (I tihnk). I'm not sure why my browser was still working; probably aggressive caching. Anyways, thanks to both of you.

**Comment by travisdowns** [comment]
All the examples show up for me now, thanks. I don't Privacy Bager, but I do have Adblock Plus on both Chrome and FF, so maybe that was doing it (too late to confirm now).
