### ISSUE TITLE
MSVC with /Zc:__cplusplus and deprecated on a friend function does not compile

### ISSUE THREAD

**Issue by t-b** [nemequ/hedley#33]
I'm coming from https://github.com/nlohmann/json/issues/1695.

The problem is that `HEDLEY_DEPRECATED_FOR` does not work in some cases for MSVC when /Zc:__cplusplus is set. https://godbolt.org/z/zh8AJB is a short example demonstrating the issue and https://github.com/nlohmann/json/pull/1958 is a PR which currently fails due to that.

**Comment by nemequ** [comment]
Interesting.  [Looks like](https://godbolt.org/z/7PLfya) this was fixed in VS2019.

There is really no way to control which implementation is used based on where it is in the code (*i.e.,*, we can't use __declspec on friends but an attribute elsewhere).  In this case, though, I don't see much reason to prefer a C++ attribute over the declspec version, so how about just prioritizing the declspec version by moving the check to before the C++ version check?

```diff
diff --git a/hedley.h b/hedley.h
index 2ce91f3..db73760 100644
--- a/hedley.h
+++ b/hedley.h
@@ -928,7 +928,10 @@
 #if defined(HEDLEY_DEPRECATED_FOR)
 #  undef HEDLEY_DEPRECATED_FOR
 #endif
-#if defined(__cplusplus) && (__cplusplus >= 201402L)
+#if HEDLEY_MSVC_VERSION_CHECK(14,0,0)
+#  define HEDLEY_DEPRECATED(since) __declspec(deprecated("Since " # since))
+#  define HEDLEY_DEPRECATED_FOR(since, replacement) __declspec(deprecated("Since " #since "; use " #replacement))
+#elif defined(__cplusplus) && (__cplusplus >= 201402L)
 #  define HEDLEY_DEPRECATED(since) HEDLEY_DIAGNOSTIC_DISABLE_CPP98_COMPAT_WRAP_([[deprecated("Since " #since)]])
 #  define HEDLEY_DEPRECATED_FOR(since, replacement) HEDLEY_DIAGNOSTIC_DISABLE_CPP98_COMPAT_WRAP_([[deprecated("Since " #since "; use " #replacement)]])
 #elif \
@@ -962,9 +965,6 @@
   HEDLEY_TI_CLPRU_VERSION_CHECK(2,1,0)
 #  define HEDLEY_DEPRECATED(since) __attribute__((__deprecated__))
 #  define HEDLEY_DEPRECATED_FOR(since, replacement) __attribute__((__deprecated__))
-#elif HEDLEY_MSVC_VERSION_CHECK(14,0,0)
-#  define HEDLEY_DEPRECATED(since) __declspec(deprecated("Since " # since))
-#  define HEDLEY_DEPRECATED_FOR(since, replacement) __declspec(deprecated("Since " #since "; use " #replacement))
 #elif \
   HEDLEY_MSVC_VERSION_CHECK(13,10,0) || \
   HEDLEY_PELLES_VERSION_CHECK(6,50,0)
```

**Comment by t-b** [comment]
@nemequ Sounds good! Thanks for the quick reply.

**Comment by nemequ** [comment]
I just tagged v13, this workaround is included.

**Comment by t-b** [comment]
@nemequ Thanks!
