### ISSUE TITLE
Add a LICENSE File to clarify the LICENSE

### ISSUE THREAD

**Issue by mame98** [nemequ/hedley#34]
On the Website it says that hedley is Licensed under CC0:

> CC0, which is basically an attempt to put it in the public domain, or as close as possible.

It would be great if you could add a `LICENSE` or `COPYING` file to make licensing more clear from within the code.

**Comment by nemequ** [comment]
Good point, thanks.  I just pushed 24576ef7ec4742ac5188c118dd294ad920e5122e to dev for this.

If you're actually worried about the license of the code, not just discoverability, it's worth noting that their is a comment in hedley.h that specifies CC0, and even includes an [SPDX](https://spdx.org/) identifier.  I think even the most anal lawyer would be okay with that.
