### ISSUE TITLE
HEDLEY_FLAGS fallback

### ISSUE THREAD

**Issue by mattyclarkson** [nemequ/hedley#37]
```
#if HEDLEY_HAS_ATTRIBUTE(flag_enum)
#  define HEDLEY_FLAGS __attribute__((__flag_enum__))
#endif
```

When `HEDLEY_HAS_ATTRIBUTE(flag_enum)` is false we should provide a fallback for compilers that do not support the attribute.

```
#if HEDLEY_HAS_ATTRIBUTE(flag_enum)
#  define HEDLEY_FLAGS __attribute__((__flag_enum__))
#else
#  define HEDLEY_FLAGS
#endif
```

**Comment by nemequ** [comment]
Oops!  Thanks for reporting this.

I'm rather surprised CI didn't catch this…  Anyways, I've pushed a fix to the dev branch, it will be included in the next release.

If you need a temporary workaround in your code, you could always just do

```c
#if !defined(HEDLEY_FLAGS)
#  define HEDLEY_FLAGS
#endif
```
