### ISSUE TITLE
Please use github release mechanism in addition to the named tags

### ISSUE THREAD

**Issue by YarikTH** [nemequ/hedley#43]
I'm trying to automate dependencies checking and luckily almost all my dependencies are hosted on Github, including hedley.
I found a way to request the latest release version from the GitHub via the following request:
`curl --silent "https://api.github.com/repos/${LIB}/releases/latest" | jq -r .tag_name`
Unfortunately, hedley doesn't have any releases. Only tags, so this doesn't work. And I'm not sure that "get the latest tag that looks like a release" exist.
Can I have at least latest tag as a release, please? I'm not sure if someone else interested in it though.

**Comment by nemequ** [comment]
Done, I think.  I'm closing the issue, but obviously feel free to re-open if that didn't do the trick.

Also, note that development is done in branches; the default branch (currently "master", but I'll be [switching to "main"](https://github.com/github/renaming) soon) contains the latest stable release.
