### ISSUE TITLE
Warning and message macros.

### ISSUE THREAD

**Issue by nemequ** [nemequ/hedley#5]
See nemequ/portable-snippets#17 for original issue.

`#warning` is non-standard, and also you can't put it in a macro like you can with pragmas.

GCC 4.4, ICC, and clang support `#pragma message …`. suncc, armcc, pgcc, and xlc don't. MSVC supports `#pragma message(…)`

GCC 4.8 and ICC support `#pragma GCC warning …`. Clang kind of supports it, but [treats it as an alias for `#pragma message ...`](https://bugs.llvm.org/show_bug.cgi?id=36758). `#pragma clang warning …` works as expected, though.

Clang doesn't have a `__has_pragma()` macro, and the version numbers are useless (thanks, Apple), but we can do something like

```c
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma message "Message"
#pragma clang diagnostic pop
```

I think MSVC treats `#pragma message(…)` as a warning instead of an informational message. Research required :(

So, maybe something like

```c
#if defined(HEDLEY_MESSAGE)
#  undef HEDLEY_MESSAGE
#endif
#if HEDLEY_GCC_VERSION_CHECK(4,4,0) || HEDLEY_INTEL_VERSION_CHECK(16,0,0)
#  define HEDLEY_MESSAGE(msg) HEDLEY_PRAGMA(message msg)
#elif HEDLEY_CLANG_HAS_WARNING("-Wunknown-pragmas")
#  define HEDLEY_MESSAGE(msg) \
  HEDLEY_DIAGNOSTIC_PUSH \
  _Pragma("clang diagnostic ignored \"-Wunknown-pragmas\"") \
  HEDLEY_PRAGMA(message msg) \
  HEDLEY_DIAGNOSTIC_POP
#else
#  define HEDLEY_MESSAGE(msg)
#endif

#if defined(HEDLEY_WARNING)
#  undef HEDLEY_WARNING
#endif
#if HEDLEY_GCC_VERSION_CHECK(4,8,0) || HEDLEY_INTEL_VERSION_CHECK(16,0,0)
#  define HEDLEY_WARNING(msg) HEDLEY_PRAGMA(GCC warning msg)
#elif HEDLEY_CLANG_HAS_WARNING("-Wunknown-pragmas")
#  define HEDLEY_WARNING(msg) \
  HEDLEY_DIAGNOSTIC_PUSH \
  _Pragma("clang diagnostic ignored \"-Wunknown-pragmas\"") \
  HEDLEY_PRAGMA(clang warning msg) \
  HEDLEY_DIAGNOSTIC_POP
#elif HEDLEY_MSVC_VERSION_CHECK(15,0,0)
#  define HEDLEY_WARNING(msg) HEDLEY_PRAGMA(message(msg))
#else
#  define HEDLEY_WARNING(msg) HEDLEY_MESSAGE(msg)
#endif
```

**Comment by nemequ** [comment]
Just tested MSVC, `#pragma message(…)` is an informational message not a warning, and I don't see a way to generate a warning.

I've pushed a version of this to the dev branch. @travisdowns, what do you think?

**Comment by travisdowns** [comment]
What's the practical difference between warning and message on most of these compilers? The warnings are prefixed with some text like `warning:` or go to `stderr` rather than `stdout` or something like that?

Overall it seems good. Right now warning and message are totally distinct, right? Like if a compiler supports a warning mechanism but not a message one, `HEDLEY_MESSAGE` will never try to use the warning mechanism to output the message, right?

I think at least some users would want to output messages "best effort" even using the wrong mechanism if the right one wasn't available since I think the practical difference between the different output types isn't big.

**Comment by travisdowns** [comment]
> a warning should cause the build to fail whereas a message shouldn't.

Oh right, that's a really important distinction that I hadn't considered.


> HEDLEY_WARNING falls back on HEDLEY_MESSAGE if the compiler doesn't know how to emit a warning (like for MSVC). However, if a compiler supports warnings but not messages HEDLEY_MESSAGE should be silent instead of generating a warning.

Yeah now I see it in the above code. Given what you said about warnings-as-errors, this seems like the best approach.

**Comment by nemequ** [comment]
v4 (just released) has `HEDLEY_MESSAGE` and `HEDLEY_WARNING`
