### ISSUE TITLE
license question CC0-1.0

### ISSUE THREAD

**Issue by svmobi** [nemequ/hedley#52]
we are using nlohman json [https://github.com/nlohmann/json](url) (licensed MIT) in a commercial project, which itself includes hedley. Now i just want to make sure if there are any trademark or patentrights on hedley ?

**Comment by nemequ** [comment]
Nope, feel free to use it however you want.  I don't own any trademarks, and I'm not aware of any relevant patents.  All Hedley really does is expose features provided by compilers in a way that doesn't break compatibility with other compilers, I honestly can't see how anything Hedley itself does could be patentable.

Closing, but feel free to reopen if you have any follow up questions.
