### ISSUE TITLE
Per-compiler(-class?) attribute pass-thru

### ISSUE THREAD

**Issue by aghast** [nemequ/hedley#61]
A scan of the issues list shows a bunch of requests for very specific per-compiler attributes. Worse yet, I just came up against the problem myself, with a GCC attribute I would like to pass through, but of course only in GCC and GCC-emulating hosts. Hedley, help me!

I'd like a pass-through macro that works for a target platform. Something like:

    HEDLEY_IF(GCC, alloc_size(3))

The point would be to pass through the attribute only on GCC hosts. It should be fairly easy to extend to MSVC, IAR, etc. by changing the first argument. Basically, if you have an attribute that only works on target X, it should be possible to have it active only on target X with Hedley, without having to do the `#ifdef` dance.

**Comment by nemequ** [comment]
I'm sympathetic to the idea of wanting Hedley to provide a way to help you do this, but I think the result would be just as ugly (and, frankly, a little less readable) than just doing something like

```c++
#if HEDLEY_GCC_VERSION_CHECK(4,3,0)
#  define MY_ALLOC_SIZE(n) __attribute__((__alloc_size__(n)))
#endif
```

A big part of the benefit of Hedley is to move all those conditionals away from the code, and while this would be a slightly less verbose syntax it would still keep all that logic in the code of people using Hedley :(

For this specific example, I don't see a reason not to add a `HEDLEY_ALLOC_SIZE(n)` macro. For one thing, it's not just a GCC thing; clang supports it too. So maybe something like (untested)

```c
#if HEDLEY_GCC_VERSION_CHECK(4,3,0) || HEDLEY_HAS_ATTRIBUTE(alloc_size)
#  define HEDLEY_ALLOC_SIZE(...) __alloc_size__((__VA_ARGS__))
#else
#  define HEDLEY_ALLOC_SIZE(...)
#endif
```

**Comment by nemequ** [comment]
a9229ef2e9ed149d51e3ec8a40261254c8bd1984 adds a `HEDLEY_ALLOC_SIZE` macro. It will be included in the next release (16)
